### ISSUE TITLE
error when flashing

### ISSUE THREAD

**Issue by nqd** [jimparis/adi-cm3sd#1]
Hi Jim,

Working with contiki ADuCRF101, when programming a hex file with Segger emulator, I got this error

```
python adi-cm3sd/cm3sd.py -a contiki/examples/hello-world/hello-world.ev-aducrf101mkxz /dev/serial/by-id/usb-SEGGER_J-Link_000541001507-if00
Hold BOOT and press RESET.
Waiting for bootloader... ok
Chip: 'ADuCRF101  128 ' revision 'E30'
Bulk erase... ok
Traceback (most recent call last):
  File "adi-cm3sd/cm3sd.py", line 282, in <module>
    cm3sd.write(hexfile)
  File "adi-cm3sd/cm3sd.py", line 196, in write
    ih = ihex.IHex.read(hexfile)
  File "/home/nqd/workspaces/adi-cm3sd/ihex/__init__.py", line 15, in read
    t, a, d = ihex.parse_line(line)
  File "/home/nqd/workspaces/adi-cm3sd/ihex/__init__.py", line 123, in parse_line
    raise ValueError("Invalid line start character (%r)" % rawline[0])
ValueError: Invalid line start character ('\x7f')
```

I think cm3sd fail to read the hex file. What is your suggestion to fix this?

Thanks,

NQDinh

**Comment by jimparis** [comment]
Hi NQDinh,

The file `hello-world.ev-aducrf101mkxz` is probably an ELF file, not a HEX file.  You need to build `hello-world.ev-aducrf101mkxz.hex` instead (the Contiki build system should handle that, if you specify it as a target).  Then `cm3sd.py` should work!

Jim

**Comment by nqd** [comment]
```
    thank jim,it works well then.many thanks again.nqdinh



     ---- On Wed, 14 Jan 2015 17:24:30 -0800  notifications@github.com  wrote ----Hi NQDinh,
```

The file hello-world.ev-aducrf101mkxz is probably an ELF file, not a HEX file.  You need to build hello-world.ev-aducrf101mkxz.hex instead (the Contiki build system should handle that, if you specify it as a target).  Then cm3sd.py should work!
Jim
